Repository langleyfoxall/technologies, pull requests merged in 2018-10, with the labels that each got.

#42 Breadcrumb initial integration
  _config.yml
  _includes/nav-breadcrumb-icon.svg
  _includes/nav-breadcrumbs.html
  _layouts/default.html
  _plugins/breadcrumbs.rb
  _plugins/drops/breadcrumb_item.rb
Labels: enhancement

#54 Update where opening brace goes on method declaration
  platforms/web/php/standards.md
Labels: enhancement

#51 Initial UWP Documentation.
  platforms/desktop/windows.md
Labels: enhancement

#55 Start general programming practices
  general/programming-practices.md
Labels: enhancement

#52 Fix footer and empty breadcrumb header
  _layouts/default.html
  assets/css/style.scss
Labels: enhancement

#44 Start Fastlane & Match documentation
  platforms/mobile/ios/fastlane/core.md
  platforms/mobile/ios/fastlane/match.md
  platforms/mobile/ios/ios.md
Labels: enhancement, restructure

#57 Fix the iOS link on the main README.md
  README.md
Labels: bug

#73 Fix links to styleguides
  platforms/web/web.md
  styleguides/javascript/core.md
  styleguides/php/Laravel.md
  styleguides/php/laravel.md
Labels: bug, enhancement
